//! Renders the generated artefacts. The `gen` binary writes them to disk or,
//! with `--check`, fails if the checked-in copies differ.

use crate::{frames, rest};
use schemars::generate::SchemaSettings;
use ts_rs::{Config, TS};

/// Repository-relative path of the generated JSON Schema.
pub const SCHEMA_PATH: &str = "schema/hennery-protocol.schema.json";
/// Repository-relative path of the generated TypeScript module.
pub const TS_PATH: &str = "web/src/generated/protocol.ts";

const HEADER: &str = "// Generated by `cargo run -p hennery-proto --bin gen`. Do not edit.\n";

/// One JSON Schema document with every top-level type under `$defs`.
pub fn render_schema() -> String {
    let mut generator = SchemaSettings::draft2020_12().into_generator();
    let mut defs = serde_json::Map::new();
    macro_rules! add {
        ($($t:ty),* $(,)?) => {$(
            let schema = generator.root_schema_for::<$t>();
            defs.insert(stringify!($t).rsplit("::").next().unwrap().to_string(), schema.to_value());
        )*};
    }
    add!(
        frames::HostFrame,
        frames::CollectorFrame,
        rest::StartSessionRequest,
        rest::StartSessionResponse,
        rest::PromptRequest,
        rest::PromptResponse,
        rest::EventDto,
        rest::ApiError,
    );
    let doc = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "hennery protocol",
        "$defs": defs,
    });
    let mut out = serde_json::to_string_pretty(&doc).expect("schema serializes");
    out.push('\n');
    out
}

/// One TypeScript module exporting every hennery wire type.
pub fn render_ts() -> String {
    let cfg = Config::default();
    let mut out = String::from(HEADER);
    macro_rules! add {
        ($($t:ty),* $(,)?) => {$(
            out.push_str("\nexport ");
            out.push_str(&<$t as TS>::decl(&cfg));
            out.push('\n');
        )*};
    }
    add!(
        frames::AttachedSession,
        frames::TurnOutcome,
        frames::Indexed,
        frames::SessionBody,
        frames::HostFrame,
        frames::CollectorFrame,
        rest::StartSessionRequest,
        rest::StartSessionResponse,
        rest::PromptRequest,
        rest::PromptResponse,
        rest::EventDto,
        rest::ApiError,
    );
    out
}
