//! Renders the generated artefacts. The `gen` binary writes them to disk or,
//! with `--check`, fails if the checked-in copies differ.

use crate::{frames, rest};
use schemars::generate::SchemaSettings;
use ts_rs::{Config, TS};

/// Repository-relative path of the generated JSON Schema.
pub const SCHEMA_PATH: &str = "schema/hennery-protocol.schema.json";
/// Repository-relative path of the generated TypeScript module.
pub const TS_PATH: &str = "web/src/generated/protocol.ts";

const HEADER: &str = "// Generated by `cargo run -p hennery-proto --bin gen`. Do not edit.\n";

/// One JSON Schema document with every type under one flat, top-level
/// `$defs`.
///
/// Each root type is added via [`SchemaGenerator::subschema_for`] on a
/// single shared generator, which records `T` itself (unless inlined) plus
/// everything `T` transitively depends on in the generator's own flat
/// `definitions` map (schemars 1.2 `src/generate.rs`). We then drain that
/// map with `take_definitions` instead of using `root_schema_for`, which
/// would embed a *fresh copy* of the accumulated definitions under each
/// root's own nested `$defs` — producing dangling `#/$defs/...` refs at the
/// document root, since only the root types themselves would be registered
/// there.
pub fn render_schema() -> String {
    let mut generator = SchemaSettings::draft2020_12().into_generator();
    macro_rules! add {
        ($($t:ty),* $(,)?) => {$(
            generator.subschema_for::<$t>();
        )*};
    }
    add!(
        frames::HostFrame,
        frames::CollectorFrame,
        rest::StartSessionRequest,
        rest::StartSessionResponse,
        rest::PromptRequest,
        rest::PromptResponse,
        rest::EventDto,
        rest::ApiError,
    );
    // BTreeMap, not the generator's own serde_json::Map, so key order is
    // deterministic regardless of whether some dependency enables
    // schemars/serde_json's `preserve_order` feature.
    let defs: std::collections::BTreeMap<String, serde_json::Value> =
        generator.take_definitions(true).into_iter().collect();
    let doc = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "hennery protocol",
        "$defs": defs,
    });
    let mut out = serde_json::to_string_pretty(&doc).expect("schema serializes");
    out.push('\n');
    out
}

/// One TypeScript module exporting every hennery wire type.
pub fn render_ts() -> String {
    let cfg = Config::default();
    let mut out = String::from(HEADER);
    macro_rules! add {
        ($($t:ty),* $(,)?) => {$(
            out.push_str("\nexport ");
            out.push_str(&<$t as TS>::decl(&cfg));
            out.push('\n');
        )*};
    }
    add!(
        frames::AttachedSession,
        frames::TurnOutcome,
        frames::Indexed,
        frames::SessionBody,
        frames::HostFrame,
        frames::CollectorFrame,
        rest::StartSessionRequest,
        rest::StartSessionResponse,
        rest::PromptRequest,
        rest::PromptResponse,
        rest::EventDto,
        rest::ApiError,
    );
    out
}
