//! Renders the generated artefacts. The `gen` binary writes them to disk or,
//! with `--check`, fails if the checked-in copies differ.

use crate::{frames, rest};
use schemars::generate::SchemaSettings;
use ts_rs::{Config, TS};

/// Repository-relative path of the generated JSON Schema.
pub const SCHEMA_PATH: &str = "schema/hennery-protocol.schema.json";
/// Repository-relative path of the generated TypeScript module.
pub const TS_PATH: &str = "web/src/generated/protocol.ts";

const HEADER: &str = "// Generated by `cargo run -p hennery-proto --bin gen`. Do not edit.\n";

/// One JSON Schema document with every type under one flat, top-level
/// `$defs`.
///
/// Each root type is added via [`SchemaGenerator::subschema_for`] on a
/// single shared generator, which records `T` itself (unless inlined) plus
/// everything `T` transitively depends on in the generator's own flat
/// `definitions` map (schemars 1.2 `src/generate.rs`). We then drain that
/// map with `take_definitions` instead of using `root_schema_for`, which
/// would embed a *fresh copy* of the accumulated definitions under each
/// root's own nested `$defs` — producing dangling `#/$defs/...` refs at the
/// document root, since only the root types themselves would be registered
/// there.
pub fn render_schema() -> String {
    let mut generator = SchemaSettings::draft2020_12().into_generator();
    macro_rules! add {
        ($($t:ty),* $(,)?) => {$(
            generator.subschema_for::<$t>();
        )*};
    }
    add!(
        frames::HostFrame,
        frames::CollectorFrame,
        rest::StartSessionRequest,
        rest::StartSessionResponse,
        rest::PromptRequest,
        rest::PromptResponse,
        rest::StoredBlock,
        rest::AttachmentUsage,
        rest::EventDto,
        rest::ApiError,
        rest::LifecycleResponse,
        rest::SessionItem,
        rest::SessionPage,
        rest::SessionDetail,
        rest::CancelResponse,
        rest::ConfigRequest,
        rest::SessionCatalog,
        rest::PendingItem,
        rest::AnswerRequest,
        rest::AnswerResponse,
        rest::PairingCodeResponse,
        rest::EnrollRequest,
        rest::EnrollResponse,
        rest::HostItem,
        rest::RecentProject,
        rest::HostProjects,
        rest::DirectoryListing,
        rest::SetupRequest,
        rest::SetupResponse,
        rest::LoginRequest,
        rest::StepUpRequest,
        rest::AuthSessionItem,
        rest::PasskeyRegisterRequest,
        rest::PasskeyCeremony,
        rest::PasskeyFinishRequest,
        rest::PasskeyItem,
        rest::UpdateHostRequest,
        rest::HatItem,
        rest::PurgePreview,
        rest::PurgeResult,
        rest::CreateHatRequest,
        rest::UpdateHatRequest,
        rest::SetHatLogoRequest,
        rest::PathRuleItem,
        rest::PathRuleInput,
        rest::PathRulesRequest,
        rest::HatResolveRequest,
        rest::HatResolution,
        rest::UpdateSessionRequest,
        rest::VapidKeyResponse,
        rest::PushKeys,
        rest::PushSubscribeRequest,
        rest::PushRotateRequest,
        rest::PushUnsubscribeRequest,
        rest::PushSubscriptionItem,
        rest::PushPolicyRequest,
        rest::PushPolicyItem,
        rest::SettingsResponse,
        rest::SettingsUpdateRequest,
        rest::SettingsUpdateResponse,
        rest::PublicUrlChanged,
        rest::PushPayload,
        rest::McpCredKind,
        rest::McpConnectionStatus,
        rest::McpConnectionItem,
        rest::CreateMcpConnectionRequest,
        rest::UpdateMcpConnectionRequest,
        rest::McpMountsRequest,
        rest::McpCredentialRequest,
        rest::DeleteResult,
        rest::HostRemovalItem,
        rest::DeploymentMode,
        rest::CapabilitiesResponse,
        rest::McpOauthState,
        rest::McpOauthPendingClient,
        rest::McpOauthError,
        rest::McpOauthRedirect,
        rest::McpOauthClientRequest,
        rest::McpAuthorizeRequest,
        rest::McpAuthorizeResponse,
    );
    // `serde_json::Map` is a `BTreeMap` (always iterates sorted) by default,
    // or an `IndexMap` (iterates in insertion order) when serde_json's
    // `preserve_order` feature is enabled anywhere in the build — and Cargo
    // unifies features across a shared dependency for the whole
    // compilation, so `-p hennery-proto` alone (preserve_order never
    // enabled) and a workspace build (`agent-client-protocol-schema` enables
    // it) render byte-different documents for the same types: every object
    // literal here (this `json!`, and every nested object schemars built
    // while generating `defs`) is affected, not just the top-level `$defs`.
    // `sort_keys` recursively canonicalizes every object in the whole
    // document, at every depth, so the rendered output is identical either
    // way.
    let defs: std::collections::BTreeMap<String, serde_json::Value> =
        generator.take_definitions(true).into_iter().collect();
    let doc = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "hennery protocol",
        "$defs": defs,
    });
    let mut out = serde_json::to_string_pretty(&sort_keys(doc)).expect("schema serializes");
    out.push('\n');
    out
}

/// Rebuild every object in `value`, at every depth, inserting its keys in
/// sorted order. Insertion order is what a `serde_json::Map` actually
/// iterates in when it is backed by an `IndexMap` (the `preserve_order`
/// feature); a plain `BTreeMap`-backed `Map` already iterates sorted, so
/// this is a no-op change in output for that build either way.
fn sort_keys(value: serde_json::Value) -> serde_json::Value {
    match value {
        serde_json::Value::Object(map) => {
            // A `BTreeMap` always iterates in sorted key order regardless of
            // which `Map` implementation built it.
            let sorted: std::collections::BTreeMap<String, serde_json::Value> =
                map.into_iter().map(|(key, v)| (key, sort_keys(v))).collect();
            serde_json::Value::Object(sorted.into_iter().collect())
        }
        serde_json::Value::Array(items) => serde_json::Value::Array(items.into_iter().map(sort_keys).collect()),
        other => other,
    }
}

/// One TypeScript module exporting every hennery wire type, each with its
/// own doc comment above it, as ts-rs's own export writes it (plan 8a: the
/// frontend reads a route's answers and error codes there). `decl` carries
/// only the fields' docs.
pub fn render_ts() -> String {
    let cfg = Config::default();
    let mut out = String::from(HEADER);
    macro_rules! add {
        ($($t:ty),* $(,)?) => {$(
            out.push('\n');
            out.push_str(&<$t as TS>::docs().unwrap_or_default());
            out.push_str("export ");
            out.push_str(&<$t as TS>::decl(&cfg));
            out.push('\n');
        )*};
    }
    add!(
        frames::ConfigValue,
        frames::SessionConfig,
        frames::Capability,
        frames::Capabilities,
        frames::NameValue,
        frames::McpServer,
        frames::McpDelivery,
        frames::McpIsolation,
        frames::AgentIsolation,
        frames::AttachedSession,
        frames::TurnOutcome,
        frames::ParkReason,
        frames::PendingKind,
        frames::PendingResolution,
        frames::PendingReason,
        frames::ElicitationAction,
        frames::PendingExtract,
        frames::Indexed,
        frames::SessionBody,
        frames::Project,
        frames::DirEntry,
        frames::AgentHome,
        frames::ForgetKind,
        frames::ForgetReason,
        frames::ForgetWhat,
        frames::ForgetRemaining,
        frames::ForgetOutcome,
        frames::HostFrame,
        frames::CollectorFrame,
        rest::StartSessionRequest,
        rest::StartSessionResponse,
        rest::PromptRequest,
        rest::PromptResponse,
        rest::StoredBlock,
        rest::AttachmentUsage,
        rest::EventDto,
        rest::ApiError,
        rest::LifecycleResponse,
        rest::OpenTurn,
        rest::SessionItem,
        rest::SessionPage,
        rest::SessionDetail,
        rest::CancelResponse,
        rest::ConfigRequest,
        rest::SessionCatalog,
        rest::PendingState,
        rest::PendingItem,
        rest::AnswerRequest,
        rest::AnswerResponse,
        rest::PairingCodeResponse,
        rest::EnrollRequest,
        rest::EnrollResponse,
        rest::HostItem,
        rest::RecentProject,
        rest::HostProjects,
        rest::DirectoryListing,
        rest::SetupRequest,
        rest::SetupResponse,
        rest::LoginRequest,
        rest::StepUpRequest,
        rest::AuthSessionItem,
        rest::PasskeyRegisterRequest,
        rest::PasskeyCeremony,
        rest::PasskeyFinishRequest,
        rest::PasskeyItem,
        rest::UpdateHostRequest,
        rest::HatItem,
        rest::PurgePreview,
        rest::PurgeResult,
        rest::CreateHatRequest,
        rest::UpdateHatRequest,
        rest::SetHatLogoRequest,
        rest::PathRuleItem,
        rest::PathRuleInput,
        rest::PathRulesRequest,
        rest::HatResolveRequest,
        rest::HatResolution,
        rest::UpdateSessionRequest,
        rest::VapidKeyResponse,
        rest::PushKeys,
        rest::PushSubscribeRequest,
        rest::PushRotateRequest,
        rest::PushUnsubscribeRequest,
        rest::PushSubscriptionItem,
        rest::PushPolicyRequest,
        rest::PushPolicyItem,
        rest::SettingsResponse,
        rest::SettingsUpdateRequest,
        rest::SettingsUpdateResponse,
        rest::PublicUrlChanged,
        rest::PushPayload,
        rest::McpCredKind,
        rest::McpConnectionStatus,
        rest::McpConnectionItem,
        rest::CreateMcpConnectionRequest,
        rest::UpdateMcpConnectionRequest,
        rest::McpMountsRequest,
        rest::McpCredentialRequest,
        rest::RemovalState,
        rest::RemovalPending,
        rest::RemovalItem,
        rest::TranscriptRemoval,
        rest::DeleteResult,
        rest::HostRemovalState,
        rest::HostRemovalItem,
        rest::HostTranscripts,
        rest::DeploymentMode,
        rest::CapabilitiesResponse,
        rest::McpOauthState,
        rest::McpOauthPendingClient,
        rest::McpOauthError,
        rest::McpOauthRedirect,
        rest::McpOauthClientRequest,
        rest::McpAuthorizeRequest,
        rest::McpAuthorizeResponse,
    );
    out
}
