//! Renders the view's generated artefacts (plan 4a-ii; the review's A9).
//! The `gen-view` binary writes them to disk or, with `--check`, fails if the
//! checked-in copies differ.
//!
//! The protocol's types the items name (`SessionItem`, `StoredBlock` and
//! the pending enums) are `hennery-proto`'s: the TypeScript imports them
//! from its module, and the schema carries them among its `$defs`.

use crate::api::{ItemPage, ItemRemoved, SessionRemoved, SessionSummary, SummaryPage, TurnContent, WaitingChanged};
use crate::item::{
    Body, Field, FieldKind, FieldOption, Item, Location, Marker, MarkerKind, Pairing, PairingKind, PermissionOption,
    PlanEntry, Question, Request, Text, ToolCall, ToolContent, Unrecognised,
};
use hennery_proto::codegen::sort_keys;
use schemars::generate::SchemaSettings;
use ts_rs::{Config, TS};

/// Repository-relative path of the generated JSON Schema.
pub const SCHEMA_PATH: &str = "schema/hennery-view.schema.json";
/// Repository-relative path of the generated TypeScript module.
pub const TS_PATH: &str = "web/src/generated/view.ts";

const HEADER: &str = "// Generated by `cargo run -p hennery-view --bin gen-view`. Do not edit.\n";

/// What the module takes from the protocol's (`hennery-proto`'s `TS_PATH`).
const IMPORTS: &str = "import type { PendingKind, PendingReason, PendingState, SessionCatalog, SessionItem, StoredBlock } from \"./protocol\";\n";

/// `gen-view`'s exit statuses (the fleet's rule: each has a test).
pub const EXIT_OK: u8 = 0;
/// `--check`: a generated file differs from what it would write, or is
/// missing.
pub const EXIT_STALE: u8 = 1;
/// A generated file could not be written.
pub const EXIT_WRITE_FAILED: u8 = 2;

/// `gen-view` in the repository at `root`: write the generated files, or
/// with `check`, compare them. Its exit status, one of `EXIT_*`.
pub fn run(root: &std::path::Path, check: bool) -> u8 {
    let outputs = [(SCHEMA_PATH, render_schema()), (TS_PATH, render_ts())];
    let mut stale = false;
    for (path, content) in outputs {
        let full = root.join(path);
        if check {
            let current = std::fs::read_to_string(&full).unwrap_or_default();
            if current != content {
                eprintln!("stale generated file: {path}");
                stale = true;
            }
            continue;
        }
        let written = full
            .parent()
            .map_or(Ok(()), std::fs::create_dir_all)
            .and_then(|()| std::fs::write(&full, content));
        if let Err(err) = written {
            eprintln!("could not write {path}: {err}");
            return EXIT_WRITE_FAILED;
        }
        println!("wrote {path}");
    }
    if stale {
        eprintln!("run `cargo run -p hennery-view --bin gen-view` and commit the result");
        return EXIT_STALE;
    }
    EXIT_OK
}

/// One JSON Schema document with every view type, and every type they
/// name, under one flat, top-level `$defs`, its keys sorted at every depth
/// (as `hennery_proto::codegen::render_schema` does, and for the same
/// reason).
pub fn render_schema() -> String {
    let mut generator = SchemaSettings::draft2020_12().into_generator();
    macro_rules! add {
        ($($t:ty),* $(,)?) => {$(
            generator.subschema_for::<$t>();
        )*};
    }
    add!(
        Item,
        ItemPage,
        SessionSummary,
        SummaryPage,
        ItemRemoved,
        SessionRemoved,
        TurnContent,
        WaitingChanged
    );
    let defs: std::collections::BTreeMap<String, serde_json::Value> =
        generator.take_definitions(true).into_iter().collect();
    let doc = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "hennery view",
        "$defs": defs,
    });
    let mut out = serde_json::to_string_pretty(&sort_keys(doc)).expect("schema serializes");
    out.push('\n');
    out
}

/// One TypeScript module exporting every view type; the protocol's types
/// they name are imported.
pub fn render_ts() -> String {
    let cfg = Config::default();
    let mut out = format!("{HEADER}\n{IMPORTS}");
    macro_rules! add {
        ($($t:ty),* $(,)?) => {$(
            out.push_str("\nexport ");
            out.push_str(&<$t as TS>::decl(&cfg));
            out.push('\n');
        )*};
    }
    add!(
        Item,
        Body,
        Text,
        ToolCall,
        ToolContent,
        Location,
        PlanEntry,
        Question,
        Request,
        PermissionOption,
        Field,
        Pairing,
        PairingKind,
        FieldKind,
        FieldOption,
        Marker,
        MarkerKind,
        Unrecognised,
        ItemPage,
    );
    out.push_str(SESSION_SUMMARY_TS);
    add!(SummaryPage, ItemRemoved, SessionRemoved, TurnContent, WaitingChanged);
    out.push_str(STREAM_EVENTS_TS);
    out
}

/// Each stream's SSE event names and the data each carries (`api`'s
/// module doc): written by hand, as no Rust type names an SSE event.
const STREAM_EVENTS_TS: &str = "
/**
 * `GET /api/stream/view/sessions/{id}`: each SSE event and its data.
 * `catalog_changed` carries the session's whole catalogue, after the
 * burst's items.
 */
export type ItemStreamEvents = { item: Item, item_removed: ItemRemoved, catalog_changed: SessionCatalog, session_removed: SessionRemoved, resync_required: Record<string, never>, };

/**
 * `GET /api/stream/sessions`: each SSE event and its data.
 * `waiting_changed` ends the burst after every resume, and any burst in
 * which the count changed.
 */
export type ListStreamEvents = { session_upsert: SessionSummary, session_removed: SessionRemoved, waiting_changed: WaitingChanged, resync_required: Record<string, never>, };
";

/// `SessionSummary` in TypeScript: the protocol's `SessionItem` and one
/// field more. ts-rs writes a flattened struct's fields out in place, which
/// would leave a copy of the list item here, apart from the protocol's.
const SESSION_SUMMARY_TS: &str = "
export type SessionSummary = SessionItem & {
/**
 * An open question: the agent waits on it, in a turn or outside one,
 * whether or not an answer is queued (a question outside a turn sets
 * no `blocked` activity).
 */
question_waits: boolean, };
";

/// `SESSION_SUMMARY_TS` names every field of the summary: one more and
/// this stops compiling.
#[allow(dead_code)]
fn session_summary_ts_is_whole(summary: SessionSummary) {
    let SessionSummary {
        session: _,
        question_waits: _,
    } = summary;
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;
    use std::path::PathBuf;

    /// A scratch repository root of this test's own, never the real one.
    struct Root(PathBuf);

    impl Root {
        fn new(name: &str) -> Self {
            let root = std::env::temp_dir().join(format!("gen-view-{name}-{}", std::process::id()));
            let _ = std::fs::remove_dir_all(&root);
            std::fs::create_dir_all(&root).unwrap();
            Self(root)
        }
    }

    impl Drop for Root {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    /// Written, the files are up to date: 0, and then `--check` is 0.
    #[test]
    fn written_files_check_as_up_to_date() {
        let root = Root::new("ok");
        assert_eq!(run(&root.0, false), EXIT_OK);
        assert_eq!(std::fs::read_to_string(root.0.join(TS_PATH)).unwrap(), render_ts());
        assert_eq!(
            std::fs::read_to_string(root.0.join(SCHEMA_PATH)).unwrap(),
            render_schema()
        );
        assert_eq!(run(&root.0, true), EXIT_OK);
    }

    /// `--check` is 1 for a stale `view.ts`, a stale schema, or either
    /// missing; it writes nothing.
    #[test]
    fn a_stale_or_missing_file_checks_as_stale() {
        for (name, path) in [("ts", TS_PATH), ("schema", SCHEMA_PATH)] {
            let root = Root::new(&format!("stale-{name}"));
            assert_eq!(run(&root.0, false), EXIT_OK);
            std::fs::write(root.0.join(path), "stale").unwrap();
            assert_eq!(run(&root.0, true), EXIT_STALE, "{path}");
            assert_eq!(std::fs::read_to_string(root.0.join(path)).unwrap(), "stale");
            std::fs::remove_file(root.0.join(path)).unwrap();
            assert_eq!(run(&root.0, true), EXIT_STALE, "{path} missing");
        }
    }

    /// A file it cannot write is 2: here its directory's place is taken
    /// by a file.
    #[test]
    fn a_file_it_cannot_write_fails() {
        let root = Root::new("unwritable");
        std::fs::write(root.0.join("web"), "in the way").unwrap();
        assert_eq!(run(&root.0, false), EXIT_WRITE_FAILED);
    }

    /// Every type name the module uses is exported by it or imported from
    /// the protocol's: a type an item gains is not left undefined in the
    /// TypeScript (there is no TypeScript compiler in the Rust checks).
    #[test]
    fn every_type_the_module_names_is_exported_or_imported() {
        let ts = render_ts();
        // Without comments and string literals: they hold capitalised words
        // that are not types.
        let mut code = String::new();
        let mut rest = ts.as_str();
        while let Some(at) = rest.find("/*") {
            code.push_str(&rest[..at]);
            rest = &rest[at + rest[at..].find("*/").expect("closed comment") + 2..];
        }
        code.push_str(rest);
        let code: String = code
            .lines()
            .filter(|line| !line.trim_start().starts_with("//"))
            .collect::<Vec<_>>()
            .join("\n");
        let code: String = code.split('"').step_by(2).collect();

        let words = |text: &str| -> BTreeSet<String> {
            text.split(|c: char| !c.is_ascii_alphanumeric() && c != '_')
                .filter(|w| w.starts_with(|c: char| c.is_ascii_uppercase()))
                .map(str::to_string)
                .collect()
        };
        let mut known: BTreeSet<String> = code
            .split("export type ")
            .skip(1)
            .map(|decl| decl.split([' ', '<', '=']).next().unwrap().to_string())
            .collect();
        known.extend(words(IMPORTS.split('{').nth(1).unwrap().split('}').next().unwrap()));
        known.extend(["Array", "Record"].map(str::to_string));
        let unknown: Vec<_> = words(&code).difference(&known).cloned().collect();
        assert!(
            unknown.is_empty(),
            "named but neither exported nor imported: {unknown:?}"
        );
    }
}
