[package]
name = "hennery-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
ed25519-dalek.workspace = true
getrandom.workspace = true
hennery-proto.workspace = true
hex.workspace = true
libc = "0.2"
password-auth.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
webauthn-rs.workspace = true

[dev-dependencies]
tempfile = "3"
tracing-subscriber.workspace = true
webauthn-authenticator-rs.workspace = true
